import { Notification } from "@/types/Types";

export const notifications: Notification[] = [
  {
    id: 1,
    name: "Terry Franci",
    action: "requests permission to change",
    target: "Project - Nganter App",
    category: "Project",
    time: "5 min ago",
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    online: true,
  },
  {
    id: 2,
    name: "Alena Franci",
    action: "requests permission to change",
    target: "Project - Nganter App",
    category: "Project",
    time: "8 min ago",
    avatar: "src/images/user/user-03.jpg",
    online: true,
  },
  {
    id: 3,
    name: "Jocelyn Kenter",
    action: "requests permission to change",
    target: "Project - Nganter App",
    category: "Project",
    time: "15 min ago",
    avatar: "src/images/user/user-04.jpg",
    online: true,
  },
  {
    id: 4,
    name: "Brandon Philips",
    action: "requests permission to change",
    target: "Project - Nganter App",
    category: "Project",
    time: "1 hr ago",
    avatar: "src/images/user/user-05.jpg",
    online: false,
  },
  {
    id: 5,
    name: "Terry Franci",
    action: "requests permission to change",
    target: "Project - Nganter App",
    category: "Project",
    time: "5 min ago",
    avatar: "src/images/user/user-02.jpg",
    online: true,
  },
  {
    id: 6,
    name: "Alena Franci",
    action: "requests permission to change",
    target: "Project - Nganter App",
    category: "Project",
    time: "8 min ago",
    avatar: "src/images/user/user-03.jpg",
    online: true,
  },
  {
    id: 7,
    name: "Jocelyn Kenter",
    action: "requests permission to change",
    target: "Project - Nganter App",
    category: "Project",
    time: "15 min ago",
    avatar: "src/images/user/user-04.jpg",
    online: true,
  },
  {
    id: 8,
    name: "Brandon Philips",
    action: "requests permission to change",
    target: "Project - Nganter App",
    category: "Project",
    time: "1 hr ago",
    avatar: "src/images/user/user-05.jpg",
    online: false,
  },
];
